### ISSUE TITLE
Can't build on macOS (because of esy-skia ?)

### ISSUE THREAD

**Issue by giltho** [bryphe/revery-quick-start#68]
Hi !

I just cloned and ran `esy` inside the repo. It died with : 
<details>
    <summary>Error Message</summary>

  ```
  info building esy-skia@github:revery-ui/esy-skia#91b10c9@d41d8cd9
  error: build failed with exit code: 1
    build log:
      # esy-build-package: building: esy-skia@github:revery-ui/esy-skia#91b10c9
      # esy-build-package: pwd: /Users/sacha/.esy/3/b/esy_skia-a0d39b62
      # esy-build-package: running: 'bash' './esy/build.sh' 'darwin' '/Users/sacha/.esy/3___________________________________________________________________/i/esy_libjpeg_turbo-c41a79cc'
      ERROR:root:code for hash md5 was not found.
      Traceback (most recent call last):
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
          globals()[__func_name] = __get_hash(__func_name)
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
          raise ValueError('unsupported hash type ' + name)
      ValueError: unsupported hash type md5
      ERROR:root:code for hash sha1 was not found.
      Traceback (most recent call last):
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
          globals()[__func_name] = __get_hash(__func_name)
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
          raise ValueError('unsupported hash type ' + name)
      ValueError: unsupported hash type sha1
      ERROR:root:code for hash sha224 was not found.
      Traceback (most recent call last):
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
          globals()[__func_name] = __get_hash(__func_name)
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
          raise ValueError('unsupported hash type ' + name)
      ValueError: unsupported hash type sha224
      ERROR:root:code for hash sha256 was not found.
      Traceback (most recent call last):
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
          globals()[__func_name] = __get_hash(__func_name)
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
          raise ValueError('unsupported hash type ' + name)
      ValueError: unsupported hash type sha256
      ERROR:root:code for hash sha384 was not found.
      Traceback (most recent call last):
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
          globals()[__func_name] = __get_hash(__func_name)
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
          raise ValueError('unsupported hash type ' + name)
      ValueError: unsupported hash type sha384
      ERROR:root:code for hash sha512 was not found.
      Traceback (most recent call last):
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
          globals()[__func_name] = __get_hash(__func_name)
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
          raise ValueError('unsupported hash type ' + name)
      ValueError: unsupported hash type sha512
      Traceback (most recent call last):
        File "bin/fetch-gn", line 30, in <module>
          if sha1_of_file(dst) != sha1:
        File "bin/fetch-gn", line 24, in sha1_of_file
          h = hashlib.sha1()
      AttributeError: 'module' object has no attribute 'sha1'
      third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
      common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
      buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
      third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
      third_party/externals/zlib           @ e7afdfe128e01ca480a28f757b571957befdd962
      third_party/externals/spirv-headers  @ 661ad91124e6af2272afd00f804d8aa276e17107
      third_party/externals/jsoncpp        @ 1.0.0
      third_party/externals/googletest     @ dd43b9998e9a44a579a7aba6c1309407d1a5ed95
      third_party/externals/libjpeg-turbo  @ 1.5.3
      third_party/externals/lua            @ v5-3-4
      third_party/externals/expat          @ android-6.0.1_r55
      third_party/externals/libwebp        @ v0.6.1
      third_party/externals/spirv-tools    @ e9e4393b1c5aad7553c05782acefbe32b42644bd
      third_party/externals/rapidjson      @ af223d44f4e8d3772cb1ac0ce8bc2a132b51717f
      third_party/externals/harfbuzz       @ 1.4.2
      third_party/externals/freetype       @ fa6da7bf6dcbcfa22d2464259ad1cccee3233189
      third_party/externals/sfntly         @ b18b09b6114b9b7fe6fc2f96d8b15e8a72f66916
      third_party/externals/libpng         @ v1.6.33
      third_party/externals/imgui          @ 6384eee34f08cb7eab8d835043e1738e4adcdf75
      third_party/externals/sdl            @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
      third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
      third_party/externals/angle2         @ b001528ffa00e7c15a5002124f707570e59a5697
      third_party/externals/swiftshader    @ cbb80f5f0078a9941f3ec43e83e52c3d15a43bea
      third_party/externals/icu            @ ec9c1133693148470ffe2e5e53576998e3650c1d
      Traceback (most recent call last):
        File "tools/git-sync-deps", line 253, in <module>
          exit(main(sys.argv[1:]))
        File "tools/git-sync-deps", line 248, in main
          os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
        File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/opt/python@2/bin/python2.7', 'bin/fetch-gn']' returned non-zero exit status 1
      llvm toolset-7.0 does not need to be manually activated
      ./esy/build.sh: line 44: bin/gn: No such file or directory
      error: command failed: 'bash' './esy/build.sh' 'darwin' '/Users/sacha/.esy/3___________________________________________________________________/i/esy_libjpeg_turbo-c41a79cc' (exited with 255)
      esy-build-package: exiting with errors above...
      
    building esy-skia@github:revery-ui/esy-skia#91b10c9
  esy: exiting due to errors above
  ```

</details>

**Comment by glennsl** [comment]
Possibly a python 2 vs 3 issue? Seems like it uses python 2.7 from homebrew. Do you have that installed as the default? What does `python --version` say?

**Comment by glennsl** [comment]
You might want to try https://stackoverflow.com/questions/59269208/errorrootcode-for-hash-md5-was-not-found-when-using-any-hg-mercurial-command

**Comment by giltho** [comment]
Ah that might definitely be the reason !
Let me check if that works

**Comment by giltho** [comment]
Yep that was it !
Sorry for the noise, hope it helps if someone finds this issue in the future
