### ISSUE TITLE
esy build fail on building skia (macos)

### ISSUE THREAD

**Issue by Duncan-Britt** [bryphe/revery-quick-start#98]
Seems like someone was having a [similar problem](https://github.com/revery-ui/revery-quick-start/issues/82), but I don't know how much is applicable to me. They were using windows and I am using macOS Big Sur version 11.5.2.

Using esy version 0.6.12, when I run esy build I get this error log:
```
info esy build 0.6.12 (using package.json)
info building esy-skia@github:revery-ui/esy-skia#91c98f6@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: esy-skia@github:revery-ui/esy-skia#91c98f6
    # esy-build-package: pwd: /Users/duncanbritt/.esy/3/b/esy_skia-c3eadd32
    # esy-build-package: running: 'bash' './esy/build.sh' 'darwin' '/Users/duncanbritt/.esy/3____________________________________________________________/i/esy_libjpeg_turbo-dc3b4679'
    fatal: repository 'https://skia.googlesource.com/external/github.com/Tencent/rapidjson.git/' not found
    buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
    common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
    third_party/externals/angle2         @ b001528ffa00e7c15a5002124f707570e59a5697
    third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
    third_party/externals/expat          @ android-6.0.1_r55
    third_party/externals/freetype       @ fa6da7bf6dcbcfa22d2464259ad1cccee3233189
    third_party/externals/googletest     @ dd43b9998e9a44a579a7aba6c1309407d1a5ed95
    third_party/externals/harfbuzz       @ 1.4.2
    third_party/externals/icu            @ ec9c1133693148470ffe2e5e53576998e3650c1d
    third_party/externals/imgui          @ 6384eee34f08cb7eab8d835043e1738e4adcdf75
    third_party/externals/jsoncpp        @ 1.0.0
    third_party/externals/libjpeg-turbo  @ 1.5.3
    third_party/externals/libpng         @ v1.6.33
    third_party/externals/libwebp        @ v0.6.1
    third_party/externals/lua            @ v5-3-4
    third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
    third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
    Traceback (most recent call last):
      File "tools/git-sync-deps", line 254, in <module>
        exit(main(sys.argv[1:]))
      File "tools/git-sync-deps", line 246, in main
        git_sync_deps(deps_file_path, argv, verbose)
      File "tools/git-sync-deps", line 218, in git_sync_deps
        git_checkout_to_directory(*args)
      File "tools/git-sync-deps", line 132, in git_checkout_to_directory
        [git, 'clone', '--quiet', repo, directory])
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'clone', '--quiet', 'https://skia.googlesource.com/external/github.com/Tencent/rapidjson.git', 'third_party/externals/rapidjson']' returned non-zero exit status 128
    llvm toolset-7.0 does not need to be manually activated
    ./esy/build.sh: line 44: bin/gn: No such file or directory
    error: command failed: 'bash' './esy/build.sh' 'darwin' '/Users/duncanbritt/.esy/3____________________________________________________________/i/esy_libjpeg_turbo-dc3b4679' (exited with 255)
    esy-build-package: exiting with errors above...
    
  building esy-skia@github:revery-ui/esy-skia#91c98f6
esy: exiting due to errors above
```

Any suggestions for me would be greatly appreciated.

**Comment by glennsl** [comment]
This was [fixed a while ago in `esy-skia`](https://github.com/revery-ui/esy-skia/pull/42). But as I don't have the power to make releases you'll have to set up a manual resolution to `esy-skia`'s master branch.

**Comment by Duncan-Britt** [comment]
> This was [fixed a while ago in `esy-skia`](https://github.com/revery-ui/esy-skia/pull/42). But as I don't have the power to make releases you'll have to set up a manual resolution to `esy-skia`'s master branch.

Pardon my ignorance: I don't know what it means to set up a manual resolution or how to do it. So I was looking through the directory and found `esy.lock/index.json` and in it there seems to be a reference to esy-skia that looks like this:
```json
    "esy-skia@github:revery-ui/esy-skia#91c98f6@d41d8cd9": {
      "id": "esy-skia@github:revery-ui/esy-skia#91c98f6@d41d8cd9",
      "name": "esy-skia",
      "version": "github:revery-ui/esy-skia#91c98f6",
      "source": {
        "type": "install",
        "source": [ "github:revery-ui/esy-skia#91c98f6" ]
      },
      "overrides": [],
      "dependencies": [
        "esy-libjpeg-turbo@github:revery-ui/libjpeg-turbo#dbb3dd5@d41d8cd9",
        "@esy-cross/ninja-build@1.8.2001@d41d8cd9"
      ],
      "devDependencies": []
    },
```
Would it be a simple matter of editing this file in some way, and running `esy install` and `esy build`, or is it something else entirely?

**Comment by glennsl** [comment]
You might get away with that for a short while, but it would quickly get overwritten once you add or update a package. The right way is to add a resolution to your projects `package.json`. See https://esy.sh/docs/en/using-repo-sources-workflow.html#with-esy-packages

**Comment by snooper3012** [comment]
This problem is also in Linux:
```
$ esy build
info esy build 0.7.2 (using package.json)
info building esy-skia@github:revery-ui/esy-skia#91c98f6@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: esy-skia@github:revery-ui/esy-skia#91c98f6
    # esy-build-package: pwd: /home/enter_user_home_name/.esy/3/b/esy_skia-1c806f78
    # esy-build-package: running: 'bash' './esy/build.sh' 'linux' '/home/enter_user_home_name/.esy/3_________________________________________________________________/i/esy_libjpeg_turbo-e4385a3b'
    fatal: repository 'https://skia.googlesource.com/external/github.com/Tencent/rapidjson.git/' not found
    buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
    common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
    third_party/externals/angle2         @ b001528ffa00e7c15a5002124f707570e59a5697
    third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
    third_party/externals/expat          @ android-6.0.1_r55
    third_party/externals/freetype       @ fa6da7bf6dcbcfa22d2464259ad1cccee3233189
    third_party/externals/googletest     @ dd43b9998e9a44a579a7aba6c1309407d1a5ed95
    third_party/externals/harfbuzz       @ 1.4.2
    third_party/externals/icu            @ ec9c1133693148470ffe2e5e53576998e3650c1d
    third_party/externals/imgui          @ 6384eee34f08cb7eab8d835043e1738e4adcdf75
    third_party/externals/jsoncpp        @ 1.0.0
    third_party/externals/libjpeg-turbo  @ 1.5.3
    third_party/externals/libpng         @ v1.6.33
    third_party/externals/libwebp        @ v0.6.1
    third_party/externals/lua            @ v5-3-4
    third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
    third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
    Traceback (most recent call last):
      File "tools/git-sync-deps", line 254, in <module>
        exit(main(sys.argv[1:]))
      File "tools/git-sync-deps", line 246, in main
        git_sync_deps(deps_file_path, argv, verbose)
      File "tools/git-sync-deps", line 218, in git_sync_deps
        git_checkout_to_directory(*args)
      File "tools/git-sync-deps", line 132, in git_checkout_to_directory
        [git, 'clone', '--quiet', repo, directory])
      File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'clone', '--quiet', 'https://skia.googlesource.com/external/github.com/Tencent/rapidjson.git', 'third_party/externals/rapidjson']' returned non-zero exit status 128
    llvm toolset-7.0 does not need to be manually activated
    ./esy/build.sh: line 44: bin/gn: No such file or directory
    error: command failed: 'bash' './esy/build.sh' 'linux' '/home/enter_user_home_name/.esy/3_________________________________________________________________/i/esy_libjpeg_turbo-e4385a3b' (exited with 255)
    esy-build-package: exiting with errors above...

  building esy-skia@github:revery-ui/esy-skia#91c98f6
esy: exiting due to errors above
```
And, @glennsl, your link is broken
